# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgateway.proto\x12\x07gateway\"!\n\x0f\x45lectrodeNumber\x12\x0e\n\x06number\x18\x01 \x01(\x05\"\x1f\n\x0e\x45lectrodeState\x12\r\n\x05state\x18\x01 \x01(\x05\"Z\n\tElectrode\x12%\n\x03num\x18\x01 \x01(\x0b\x32\x18.gateway.ElectrodeNumber\x12&\n\x05state\x18\x02 \x01(\x0b\x32\x17.gateway.ElectrodeState2\x97\x01\n\x07Gateway\x12H\n\x11getElectrodeState\x12\x18.gateway.ElectrodeNumber\x1a\x17.gateway.ElectrodeState\"\x00\x12\x42\n\x11setElectrodeState\x12\x12.gateway.Electrode\x1a\x17.gateway.ElectrodeState\"\x00\x62\x06proto3')



_ELECTRODENUMBER = DESCRIPTOR.message_types_by_name['ElectrodeNumber']
_ELECTRODESTATE = DESCRIPTOR.message_types_by_name['ElectrodeState']
_ELECTRODE = DESCRIPTOR.message_types_by_name['Electrode']
ElectrodeNumber = _reflection.GeneratedProtocolMessageType('ElectrodeNumber', (_message.Message,), {
  'DESCRIPTOR' : _ELECTRODENUMBER,
  '__module__' : 'gateway_pb2'
  # @@protoc_insertion_point(class_scope:gateway.ElectrodeNumber)
  })
_sym_db.RegisterMessage(ElectrodeNumber)

ElectrodeState = _reflection.GeneratedProtocolMessageType('ElectrodeState', (_message.Message,), {
  'DESCRIPTOR' : _ELECTRODESTATE,
  '__module__' : 'gateway_pb2'
  # @@protoc_insertion_point(class_scope:gateway.ElectrodeState)
  })
_sym_db.RegisterMessage(ElectrodeState)

Electrode = _reflection.GeneratedProtocolMessageType('Electrode', (_message.Message,), {
  'DESCRIPTOR' : _ELECTRODE,
  '__module__' : 'gateway_pb2'
  # @@protoc_insertion_point(class_scope:gateway.Electrode)
  })
_sym_db.RegisterMessage(Electrode)

_GATEWAY = DESCRIPTOR.services_by_name['Gateway']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ELECTRODENUMBER._serialized_start=26
  _ELECTRODENUMBER._serialized_end=59
  _ELECTRODESTATE._serialized_start=61
  _ELECTRODESTATE._serialized_end=92
  _ELECTRODE._serialized_start=94
  _ELECTRODE._serialized_end=184
  _GATEWAY._serialized_start=187
  _GATEWAY._serialized_end=338
# @@protoc_insertion_point(module_scope)
